/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
import * as Types from '../../../graphql/index';

import { EmailsForm_UserEmailFragment } from './EmailsForm_UserEmail.graphql.hook';
import { gql } from '@apollo/client';
import { EmailsForm_UserEmailFragmentDoc } from './EmailsForm_UserEmail.graphql.hook';
export type EmailsForm_UserFragment = (
  { __typename?: 'User' }
  & Pick<Types.User, 'id'>
  & { userEmailsConnection: (
    { __typename?: 'UserEmailsConnection' }
    & { nodes: Array<(
      { __typename?: 'UserEmail' }
      & Pick<Types.UserEmail, 'id' | 'email' | 'isVerified'>
      & EmailsForm_UserEmailFragment
    )> }
  ) }
);

export const EmailsForm_UserFragmentDoc = gql`
    fragment EmailsForm_User on User {
  id
  userEmailsConnection(first: 50) {
    nodes {
      ...EmailsForm_UserEmail
      id
      email
      isVerified
    }
  }
}
    ${EmailsForm_UserEmailFragmentDoc}`;