/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
import * as Types from '../../../graphql/index';

import { gql } from '@apollo/client';
export type OrganizationPage_OrganizationFragment = (
  { __typename?: 'Organization' }
  & Pick<Types.Organization, 'id' | 'name' | 'slug' | 'currentUserIsOwner' | 'currentUserIsBillingContact'>
);

export type OrganizationPage_QueryFragment = (
  { __typename?: 'Query' }
  & { organizationBySlug: Types.Maybe<(
    { __typename?: 'Organization' }
    & Pick<Types.Organization, 'id'>
    & OrganizationPage_OrganizationFragment
  )> }
);

export const OrganizationPage_OrganizationFragmentDoc = gql`
    fragment OrganizationPage_Organization on Organization {
  id
  name
  slug
  currentUserIsOwner
  currentUserIsBillingContact
}
    `;
export const OrganizationPage_QueryFragmentDoc = gql`
    fragment OrganizationPage_Query on Query {
  organizationBySlug(slug: $slug) {
    id
    ...OrganizationPage_Organization
  }
}
    ${OrganizationPage_OrganizationFragmentDoc}`;