/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
import * as Types from '../../../graphql/index';

import { gql } from '@apollo/client';
export type OrganizationPage_OrganizationFragment = { __typename?: 'Organization', id: any, name: string, slug: string, currentUserIsOwner: boolean | null, currentUserIsBillingContact: boolean | null };

export type OrganizationPage_QueryFragment = { __typename?: 'Query', organizationBySlug: { __typename?: 'Organization', id: any, name: string, slug: string, currentUserIsOwner: boolean | null, currentUserIsBillingContact: boolean | null } | null };

export const OrganizationPage_OrganizationFragmentDoc = gql`
    fragment OrganizationPage_Organization on Organization {
  id
  name
  slug
  currentUserIsOwner
  currentUserIsBillingContact
}
    `;
export const OrganizationPage_QueryFragmentDoc = gql`
    fragment OrganizationPage_Query on Query {
  organizationBySlug(slug: $slug) {
    id
    ...OrganizationPage_Organization
  }
}
    ${OrganizationPage_OrganizationFragmentDoc}`;