/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */
import * as Types from '../../../graphql/index';

import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions =  {}
export type RemoveFromOrganizationMutationVariables = Types.Exact<{
  organizationId: Types.Scalars['UUID'];
  userId: Types.Scalars['UUID'];
}>;


export type RemoveFromOrganizationMutation = (
  { __typename?: 'Mutation' }
  & { removeFromOrganization: Types.Maybe<(
    { __typename?: 'RemoveFromOrganizationPayload' }
    & Pick<Types.RemoveFromOrganizationPayload, 'clientMutationId'>
  )> }
);


export const RemoveFromOrganizationDocument = gql`
    mutation RemoveFromOrganization($organizationId: UUID!, $userId: UUID!) {
  removeFromOrganization(
    input: {organizationId: $organizationId, userId: $userId}
  ) {
    clientMutationId
  }
}
    `;
export type RemoveFromOrganizationMutationFn = Apollo.MutationFunction<RemoveFromOrganizationMutation, RemoveFromOrganizationMutationVariables>;

/**
 * __useRemoveFromOrganizationMutation__
 *
 * To run a mutation, you first call `useRemoveFromOrganizationMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useRemoveFromOrganizationMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [removeFromOrganizationMutation, { data, loading, error }] = useRemoveFromOrganizationMutation({
 *   variables: {
 *      organizationId: // value for 'organizationId'
 *      userId: // value for 'userId'
 *   },
 * });
 */
export function useRemoveFromOrganizationMutation(baseOptions?: Apollo.MutationHookOptions<RemoveFromOrganizationMutation, RemoveFromOrganizationMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<RemoveFromOrganizationMutation, RemoveFromOrganizationMutationVariables>(RemoveFromOrganizationDocument, options);
      }
export type RemoveFromOrganizationMutationHookResult = ReturnType<typeof useRemoveFromOrganizationMutation>;
export type RemoveFromOrganizationMutationResult = Apollo.MutationResult<RemoveFromOrganizationMutation>;
export type RemoveFromOrganizationMutationOptions = Apollo.BaseMutationOptions<RemoveFromOrganizationMutation, RemoveFromOrganizationMutationVariables>;